import 'dart:io';

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'homepage.dart'; // This is generated by the Firebase CLI

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  if (Platform.isAndroid) {
    await Firebase.initializeApp(
      options: FirebaseOptions(
        apiKey: "AIzaSyCV0-NZHjm_0VZRvqEn0WhGc2Kpq49SBa8",
        appId: "1:262757508649:android:9efce8f15c47409ad9de38",
        messagingSenderId: "262757508649",
        projectId: "bara3em-ee851",
      ),
    );
  } else if (Platform.isIOS) {
    await Firebase.initializeApp();
  }
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: SimpleLoginScreen(),
    );
  }
}

class SimpleLoginScreen extends StatefulWidget {
  @override
  _SimpleLoginScreenState createState() => _SimpleLoginScreenState();
}

class _SimpleLoginScreenState extends State<SimpleLoginScreen> {
  final TextEditingController emailController = TextEditingController();
  final TextEditingController passwordController = TextEditingController();

  String? emailError;
  String? passwordError;

  bool validate() {
    setState(() {
      emailError = emailController.text.isEmpty || !RegExp(
        r"^[a-zA-Z0-9.]+@[a-zA-Z0-9]+\.[a-zA-Z]+",
      ).hasMatch(emailController.text) ? 'Enter a valid email' : null;

      passwordError = passwordController.text.isEmpty ? 'Password cannot be empty' : null;
    });

    return emailError == null && passwordError == null;
  }

  void submit() async {
    if (validate()) {
      try {
        UserCredential userCredential = await FirebaseAuth.instance.signInWithEmailAndPassword(
          email: emailController.text,
          password: passwordController.text,
        );
        Navigator.of(context).pushReplacement(MaterialPageRoute(builder: (_) => Bara3emHomePage()));
      } on FirebaseAuthException catch (e) {
        final message = e.code == 'user-not-found' || e.code == 'wrong-password'
            ? 'Invalid email or password'
            : 'Login failed, please try again later';
        showDialog(
          context: context,
          builder: (context) => AlertDialog(
            title: Text('Login Error'),
            content: Text(message),
            actions: [
              TextButton(
                child: Text('OK'),
                onPressed: () => Navigator.of(context).pop(),
              ),
            ],
          ),
        );
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Login')),
      body: SingleChildScrollView(
        padding: EdgeInsets.all(16),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            SizedBox(height: 40),
            Text('Welcome,', style: TextStyle(fontSize: 24, fontWeight: FontWeight.bold)),
            Text('Sign in to continue!', style: TextStyle(fontSize: 16, color: Colors.grey[600])),
            SizedBox(height: 20),
            TextField(
              controller: emailController,
              decoration: InputDecoration(
                labelText: 'Email',
                errorText: emailError,
                border: OutlineInputBorder(borderRadius: BorderRadius.circular(8)),
              ),
            ),
            SizedBox(height: 20),
            TextField(
              controller: passwordController,
              obscureText: true,
              decoration: InputDecoration(
                labelText: 'Password',
                errorText: passwordError,
                border: OutlineInputBorder(borderRadius: BorderRadius.circular(8)),
              ),
            ),
            SizedBox(height: 20),
            ElevatedButton(
              onPressed: submit,
              child: Text('Log In'),
              style: ElevatedButton.styleFrom(minimumSize: Size(double.infinity, 50)),
            ),
            TextButton(
              onPressed: () => Navigator.of(context).push(MaterialPageRoute(builder: (_) => SimpleRegisterScreen())),
              child: Text('Create a new account'),
            ),
          ],
        ),
      ),
    );
  }
}

class SimpleRegisterScreen extends StatefulWidget {
  @override
  _SimpleRegisterScreenState createState() => _SimpleRegisterScreenState();
}

class _SimpleRegisterScreenState extends State<SimpleRegisterScreen> {
  final TextEditingController emailController = TextEditingController();
  final TextEditingController passwordController = TextEditingController();
  final TextEditingController confirmPasswordController = TextEditingController();
  final TextEditingController nameController = TextEditingController();

  String? emailError;
  String? passwordError;

  bool validate() {
    setState(() {
      emailError = emailController.text.isEmpty || !RegExp(
        r"^[a-zA-Z0-9.]+@[a-zA-Z0-9]+\.[a-zA-Z]+",
      ).hasMatch(emailController.text) ? 'Enter a valid email' : null;

      passwordError = passwordController.text.isEmpty ? 'Password cannot be empty' :
      passwordController.text.length < 6 ? 'Password must be at least 6 characters long' : null;
    });

    return emailError == null && passwordError == null;
  }

  void submit() async {
    if (validate()) {
      try {
        UserCredential userCredential = await FirebaseAuth.instance.createUserWithEmailAndPassword(
          email: emailController.text,
          password: passwordController.text,
        );
        await userCredential.user!.updateDisplayName(nameController.text);
        Navigator.of(context).pushReplacement(MaterialPageRoute(builder: (_) => Bara3emHomePage()));
      } on FirebaseAuthException catch (e) {
        final message = e.code == 'email-already-in-use'
            ? 'The email address is already in use by another account.'
            : 'Registration failed, please try again later';
        showDialog(
          context: context,
          builder: (context) => AlertDialog(
            title: Text('Registration Error'),
            content: Text(message),
            actions: [
              TextButton(
                child: Text('OK'),
                onPressed: () => Navigator.of(context).pop(),
              ),
            ],
          ),
        );
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Register')),
      body: SingleChildScrollView(
        padding: EdgeInsets.all(16),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            SizedBox(height: 40),
            Text('Create Account,', style: TextStyle(fontSize: 24, fontWeight: FontWeight.bold)),
            Text('Sign up to get started!', style: TextStyle(fontSize: 16, color: Colors.grey[600])),
            SizedBox(height: 20),
            TextField(
              controller: emailController,
              decoration: InputDecoration(
                labelText: 'Email',
                errorText: emailError,
                border: OutlineInputBorder(borderRadius: BorderRadius.circular(8)),
              ),
            ),
            SizedBox(height: 20),
            TextField(
              controller: passwordController,
              obscureText: true,
              decoration: InputDecoration(
                labelText: 'Password',
                errorText: passwordError,
                border: OutlineInputBorder(borderRadius: BorderRadius.circular(8)),
              ),
            ),
            SizedBox(height: 20),
            TextField(
              controller: confirmPasswordController,
              obscureText: true,
              decoration: InputDecoration(
                labelText: 'Confirm Password',
                errorText: passwordError,
                border: OutlineInputBorder(borderRadius: BorderRadius.circular(8)),
              ),
            ),
            SizedBox(height: 20),
            TextField(
              controller: nameController,
              decoration: InputDecoration(
                labelText: 'Name',
                border: OutlineInputBorder(borderRadius: BorderRadius.circular(8)),
              ),
            ),
            SizedBox(height: 20),
            ElevatedButton(
              onPressed: submit,
              child: Text('Sign Up'),
              style: ElevatedButton.styleFrom(minimumSize: Size(double.infinity, 50)),
            ),
            TextButton(
              onPressed: () => Navigator.of(context).pop(),
              child: Text('Already have an account? Sign in'),
            ),
          ],
        ),
      ),
    );
  }
}
